version: '3.5'
services:
  
  contena_01:
    build: ./ubuntu
    container_name: ubuntu18.04_Remodeling
    ports:
      - "5001:5001"
    networks:
      - web
    volumes:
      - ./static:/static
    command: uwsgi --socket :5001 --module testsite.wsgi --py-autoreload 1 --logto /tmp/mylog.log  

  nginx:
    build: ./nginx
    ports:
      - "8000:8000"
    networks:
      - web
    volumes:    
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./static:/static
    depends_on:
      - contena_01

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      PGDATA: /data/postgres      
    volumes:
      - postgres:/data/postgres
    ports:
      - "${PGADMIN_PORT:-5432}:5432"
      #- "5432:5432"
    networks:
      - web
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - web
    restart: unless-stopped


networks:
  web:
    driver: bridge
    
volumes:
    ubuntu18.04_Remodeling:
    postgres:
    pgadmin:
